AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Encourager App - Lambda + API Gateway + S3 + CloudFront

Parameters:
  Environment:
    Type: String
    Default: prod
    Description: Environment name (prod, staging, dev)
  DomainName:
    Type: String
    Default: ""
    Description: Optional custom domain name
  ImageTag:
    Type: String
    Default: latest
    Description: Docker image tag for the Lambda function
  AllowedOrigin:
    Type: String
    Default: "*"
    Description: Allowed CORS origin (set to your CloudFront or custom domain URL in production)

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ASPNETCORE_ENVIRONMENT: !Ref Environment

Resources:
  EncouragerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: !Sub "'${AllowedOrigin}'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,OPTIONS'"

  VerseApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/encourager-api:${ImageTag}"
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref Environment
          ALLOWED_ORIGIN: !Ref AllowedOrigin
      Events:
        VerseApi:
          Type: Api
          Properties:
            RestApiId: !Ref EncouragerApi
            Path: /api/verse/random
            Method: GET
        HealthApi:
          Type: Api
          Properties:
            RestApiId: !Ref EncouragerApi
            Path: /api/health
            Method: GET

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "encourager-oac-${Environment}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "encourager-frontend-${Environment}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
          - Id: ApiGatewayOrigin
            DomainName: !Sub "${EncouragerApi}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: /Prod
            CustomOriginConfig:
              HTTPPort: 443
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
          Compress: true
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
                - CloudFront-Forwarded-Proto
            MinTTL: 0
            DefaultTTL: 300
            MaxTTL: 3600
        Enabled: true
        Comment: Encourager App Distribution
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${EncouragerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  CloudFrontUrl:
    Description: CloudFront distribution URL
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontUrl"

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDistributionId"

  FrontendBucketName:
    Description: S3 bucket name for frontend
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${AWS::StackName}-FrontendBucketName"

  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref VerseApiFunction
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionName"
